### ISSUE TITLE
是否考虑把限制伸缩视图最大宽度作为功能选项？

### ISSUE THREAD

**Issue by wswmsword** [hellof2e/quark-cli#15]
我开发了 [postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)，这个插件可以用 css 函数和媒体查询两种方式限制 vw 单位的最大值，以保持移动端界面在桌面端的可访问性，同时这两种方式也可以作为可选项关闭，而仅仅进行 px 向 vw 的转换。

如果感兴趣的话，我可以提一个 pr～

**Comment by sanqi-med** [comment]
> 我开发了 [postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)，这个插件可以用 css 函数和媒体查询两种方式限制 vw 单位的最大值，以保持移动端界面在桌面端的可访问性，同时这两种方式也可以作为可选项关闭，而仅仅进行 px 向 vw 的转换。
> 
> 如果感兴趣的话，我可以提一个 pr～

欢迎提交PR

**Comment by xsf0105** [comment]
有点久了，没有问题就先close了
